### ISSUE TITLE
Create bisq-newsletter@lists.bisq.network list

### ISSUE THREAD

**Issue by cbeams** [bisq-network/lists#3]
Per discussion and decisions made by @emzy and @cbeams in Slack at https://bisq.slack.com/archives/C7P9HQC56/p1510135875000221.

**Comment by Emzy** [comment]
The name has been changed to bisq-newsletter@lists.bisq.network.

The list is for the Mailchimp newsletter as a `From:` field.
So if someone responds to the newsletter we can direct the mail to all members on the list.

The mailing list is invite only and the [Archive](https://lists.bisq.network/private/bisq-newsletter/) is private. You need your maling list login to view. This is because if you reply to the newsletter you would think it is not a pubic mail.

List is up and running. 
@cbeams please do a final test then the issue can be closed.

**Comment by cbeams** [comment]
Closing as complete. Everything looks good, @Emzy. Thanks!
